### PR TITLE
Properly address CSR and CSC discrepancies across all solvers.

### LINKED ISSUE #351: Bug: P and Q ordering should be flipped in ReSolve
### Description how to reproduce the bug

All non-symmetric matrices require switching the P and Q ordering to maintain accuracy, and sometimes to work at all. I've figured out how to solve this for KLU. I will make a fix for all systems.

### Re::Solve version

develop

### System and environment details

All systems

### Additional information

_No response_

### LINKED ISSUE #354: Ensure all ReSolve solvers work on non-symmetric matrices
### Summary

Flip P and Q and L and U from KLU to cancel out the error in KLU assuming the input matrix is in CSC.

### Rationale

We want to solve asymmetric systems.
So far GLU and RocSolver work, but cuSolver does not. `testRefactor` and `testSysRefactor` are failing.

### Description

We should fix cuSolver so that we can use this new functionality.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shakedregev**
## Description
 
 _This is PR solves the symmetry discrepancies. GLU, cuSolver, and RocSolver working._
 
Closes #351 
Closes #354 
 
@pelesh 
 

 ## Proposed changes
 
 _These changes shift the default in ReSolve completely to CSR and address any discrepancies with KLU by switching L with U and P with Q. I also added asymmetric matrices to the data set for ReSolve. I think this is sorely needed, and all additions to the code should make sure they work on asymmetric matrices as well._
 
 ## Checklist
 
 _Put an `x` in the boxes that apply. You can also fill these out after creating
 the PR. If you're unsure about any of them, don't hesitate to ask. We're here
 to help! This is simply a reminder of what we are going to look for before
 merging your code._
 
- [x] All tests pass. Code tested on
     - [x] CPU backend
     - [x] CUDA backend
     - [x] HIP backend
- [x] Code compiles cleanly with flags `-Wall -Wpedantic -Wconversion -Wextra`.
- [x] The new code follows Re::Solve style guidelines.
- [x] There are unit tests for the new code.
- [x] The new code is documented.
- [ ] The feature branch is rebased with respect to the target branch.

### CODE REVIEW

File: resolve/LinSolverDirectCuSolverRf.cpp [hunk 1]
```diff
@@ -44,6 +47,110 @@ namespace ReSolve
...
+    status_cusolverrf_ = cusolverRfSetResetValuesFastMode(handle_cusolverrf_, CUSOLVERRF_RESET_VALUES_FAST_MODE_ON);
+    error_sum += status_cusolverrf_;
+    // sort L and U columns
+    for (index_type i = 0; i < n; ++i)
+    {
+      std::sort(L->getColData(memory::HOST) + L->getRowData(memory::HOST)[i],
+                L->getColData(memory::HOST) + L->getRowData(memory::HOST)[i + 1]);
+      std::sort(U->getColData(memory::HOST) + U->getRowData(memory::HOST)[i],
+                U->getColData(memory::HOST) + U->getRowData(memory::HOST)[i + 1]);
+    }
```
Comment (pelesh) [inline resolve/LinSolverDirectCuSolverRf.cpp:118]: I think `setupCsr` should require _sorted_ L and U factors in CSR format. I think this sorting should be done in the KLU class. This could be done in a follow up PR, though.

File: resolve/LinSolverDirectRocSolverRf.cpp [hunk 2]
```diff
@@ -44,6 +44,202 @@ namespace ReSolve
...
+                                                d_Q_,
+                                                rhs->getData(ReSolve::memory::DEVICE),
+                                                n,
+                                                infoM_);
+
+    mem_.deviceSynchronize();
+    error_sum += status_rocblas_;
+    // tri solve setup
+    if (solve_mode_ == 1)
+    { // OBSOLETE -- to be removed. Formerly known as "fast mode"
```
Comment (shakedregev) [inline resolve/LinSolverDirectRocSolverRf.cpp:118]:
```suggestion
    { // OBSOLETE -- to be removed. Formerly known as "fast mode" TODO
```
