### PR TITLE
Adjust resizing in vector::Vector class

### LINKED ISSUE #274: Bug: What is correct use of `n_current_` with multivectors?
### Description how to reproduce the bug

Public method `setCurrentSize(index_type n_current)` modifies `Vector` class member variable `n_current_` without reallocating the vector. This operation will be performed only if `n_current_ <= n_`, where `n_` is the size of the vector data array.

It seems that some of the other methods in `Vector` class are not using `n_current_` correctly. For example, in method `copyDataFrom` there is a line like this:
```c++
  mem_.copyArrayHostToHost(h_data_, data, n_current_ * k_);
```
Since for the multivector memory block is allocated to size `n_*k_`, vectors in the multivector start at `h_data_`, `h_data_ + n_`, `h_data_ + 2*n_`, ... . Copying `n_current_*k_` elements from `data` to the vector memory will not distribute (sub)arrays of `data` to matching vectors in the multivector, if `n_current_ < n_`.

Similar issues exist in `Vector` methods:
- `getData`
- `syncData`
- `setToZero`
- `setToConst`

It seems the only reason why this issue is not affecting computations in Re::Solve is because `setCurrentSize` is used in only two places in the code -- modified Gramm-Schmidt post-modern and 2-sync orthogonalizations. 

### Re::Solve version

`develop` branch at e42ba168aee4d5ad09b5330ffbebef2d21839d16

### System and environment details

AMD EPYC 7763 64-Core Processor, MI250X GPU, AMD clang version 18.0.0 on Linux 6.4.0.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pelesh**
## Description
 
This PR addresses several minor issues in `vector::Vector` class:
- Changes ambiguous member variable and function names.
- `getSize()` now returns vector length rather than the size of allocated memory (vector capacity)
- Default values to data ownership flags are set to `true` now.
- Resizing of vectors who do not own data (i.e. vector views of external data) is not allowed anymore.
- `getData` does not set the data ownership.

Closes #274
 

 ## Proposed changes
 
### Renamed:

Old        |    New
--------|---------
`setCurrentSize`       |  `resize`
`n_`                            | `n_capacity_`
`n_current_`             |  `n_size_`
`getSize`                   | `getCapacity`
`getCurrentSize`    | `getSize`

### Changed defaults:

Member boolean variables `owns_gpu_data_` and `owns_cpu_data_` have default values `true`. They are set to `false` only when `setData` method is invoked. Therefore `false` values of these flags indicate that the vector object is used as a "view" of data external to the vector.

Resizing of vectors who do not own their data is not allowed anymore. The owner of the data should be the only one responsible for resizing it.

### Data ownership

Public method `getData(MemorySpace m)` has the ability to bring the data to the memory space requested (host or device). It now relies on `syncData` method to copy data to the requested memory space and set correct data ownership flags, if needed.

 
 ## Checklist
  
- [x] All tests pass. Code tested on
     - [x] CPU backend
     - [x] CUDA backend
     - [x] HIP backend
- [x] Code compiles cleanly with flags `-Wall -Wpedantic -Wconversion -Wextra`.
- [x] The new code follows Re::Solve style guidelines.
- [x] There are unit tests for the new code.
- [x] The new code is documented.
- [x] The feature branch is rebased with respect to the target branch.
 
 
 ## Further comments

### CODE REVIEW

File: resolve/vector/Vector.cpp [hunk 1]
```diff
@@ -55,32 +44,38 @@ namespace ReSolve { namespace vector {
...
+    return n_capacity_;
   }
 
   /** 
-   * @brief get the current number of elements in a single vector 
-   * (use only for vectors with changing sizes, allocate for maximum expected size).
+   * @brief get the number of elements in a single vector.
+   * 
+   * For vectors with changing sizes, set the vector capacity to
+   * maximum expected size.
```
Comment (shakedregev) [inline resolve/vector/Vector.cpp:63]:
```suggestion
   * the maximum expected size.
```
