### PR TITLE
Randomized solver (both cuda and hip)

### LINKED ISSUE #84: CUDA capability not set on Ascent pipeline
It seems that CUDA capability is not set correctly on Ascent CI pipeline; should be set to 70. That causes tests to fail as newer atomic functions are not recognized with default capability.

### PR DESCRIPTION
**Pull request by kswirydo**
Working randomized GMRES with preconditioner. You can make it into FGMRES by setting flexible to 1.

Caveat: the cuda version uses ancient version of triangular solve `cusparseDcsrsv2` (I am using ILU0 preconditioner that needs triangular solve); despite my best efforts, I was not able to get the more modern version, `cusparseSpSV` to generate correct results. Hence, the code generates correct results... but uses older version of triangular solve so it compiles with tones of warnings on `deprecated` CUDA functions. I followed [this example](https://github.com/NVIDIA/cuda-samples/blob/e8568c417356f7e66bb9b7130d6be7e55324a519/Samples/4_CUDA_Libraries/conjugateGradientPrecond/main.cpp) from cuda samples to no avail. See previous commits.

What has been added:
- Two randomized classes (for fast Walsh Hadamard tranform based sketching and for Count-Sketch based sketching); cuda and hip kerneles for both,
- Randomized solver that deploys Theta (sketching).
- A cuda and hip-based examples.

To test, run `runResolveOneMatrix` with matrix of your choice (I tested with `vas_stokes_1M` from SuiteSparse).

Also fixes #84

### CODE REVIEW

**Review by pelesh — CHANGES_REQUESTED** [review]
This is great work! My main suggestion is to have functionality tests for CUDA and HIP backends implemented and added to this PR. There are a few minor issues I also mentioned in this PR.

**Comment by pelesh** [comment]
Ascent build fails with following error message:
```
Building CUDA object resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/MemoryUtils.cu.o
/gpfs/wolf/proj-shared/csc359/ci/489235/resolve/cuda/cudaKernels.cu(157): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
1 error detected in the compilation of "/gpfs/wolf/proj-shared/csc359/ci/489235/resolve/cuda/cudaKernels.cu".
make[2]: *** [resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/build.make:76: resolve/cuda/CMakeFiles/resolve_backend_cuda.dir/cudaKernels.cu.o] Error 1
```

**Comment by kswirydo** [comment]
You need cuda architecture 7.0 (or 70) to build this. Othewise atomicAdd is defined only for floats but not for doubles. Default is 5.2 somehow.

File: resolve/LinSolverDirectRocSparseILU0.cpp [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+                                                     descr_U_,
+                                                     d_ILU_vals_, //vals_, 
+                                                     A_->getRowData(ReSolve::memory::DEVICE), 
+                                                     A_->getColData(ReSolve::memory::DEVICE), 
+                                                     info_A_,
+                                                     &buffer_size_U);
+    error_sum += status_rocsparse_;
+
+    size_t buffer_size = static_cast<size_t>(max(static_cast<int>(buffer_size_A),static_cast<int>(max(static_cast<int>(buffer_size_L),static_cast<int>(buffer_size_U)))));
+    mem_.allocateBufferOnDevice(&buffer_, buffer_size);
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/LinSolverDirectRocSparseILU0.cpp:93]: if you dont cast, you get warnings. I think two values are ints and one is size_t or something like this.

File: resolve/hip/hipKernels.hip [hunk 2]
```diff
@@ -209,3 +380,43 @@ void permuteVectorQ(int n,
...
+}
+
+void FWHT_scaleByD(int n,
+                   int* D,
+                   double* x,
+                   double* y)
+{
+  hipLaunchKernelGGL(scaleByD_kernel, dim3(1000), dim3(1024), 0, 0, n, D, x, y);
+}
+
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/hip/hipKernels.hip:410]: I agree with this (I didnt optimize these kernels really ). The problem is that we have a lot kernels and each requires separate parameters so using consts/defines is probably not the way to do it(?).

File: profile.sysinfo.txt [hunk 3]
```diff
@@ -0,0 +1,307 @@
...
+=====================    
+Runtime Version:         1.1
+System Timestamp Freq.:  1000.000000MHz
+Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
+Machine Model:           LARGE                              
+System Endianness:       LITTLE                             
+
+==========               
+HSA Agents               
+==========
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply profile.sysinfo.txt:14]: idk what is it doing in commit to begin with :P

File: resolve/hip/hipKernels.hip [hunk 4]
```diff
@@ -165,12 +166,182 @@ __global__ void permuteVectorQ_kernel(const int n,
...
+    idx += blockDim.x * gridDim.x;
+  }
+}
+
+//kernels 3 and 4
+
+
+#define ELEMENTARY_LOG2SIZE 11
+namespace cg = cooperative_groups;
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/hip/hipKernels.hip:231]: this particular constant would only change if you are allowed to have more than 1024 threads per block.

File: profile.sysinfo.txt (hunk 3 above)
[the remark this answers is not in the document]
Comment (kswirydo) [reply profile.sysinfo.txt]: I removed in a commit

File: runResolveOneMatrix [hunk 5]
```diff
@@ -0,0 +1,12 @@
+#!/bin/bash
+
+
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply runResolveOneMatrix]: Documented this so it can be used by others

**Comment by cameronrutherford** [comment]
I don't know why PNNL tests aren't running, but now ORNL tests are passing @ryandanehy

File: resolve/cuda/cudaKernels.cu [hunk 6]
```diff
@@ -138,6 +139,173 @@ __global__ void matrixInfNormPart1(const int n,
...
+
+    idx += blockDim.x * gridDim.x;
+  }
+}
+
+//kernels 3 and 4
+
+
+#define ELEMENTARY_LOG2SIZE 11
+namespace cg = cooperative_groups;
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/cuda/cudaKernels.cu:198]: To be tracked in #85.

File: resolve/hip/hipKernels.hip (hunk 4 above)
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/hip/hipKernels.hip:231]: To be tracked in #85.

File: resolve/hip/hipKernels.hip (hunk 2 above)
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/hip/hipKernels.hip:410]: To be tracked in #85.

File: resolve/LinSolverIterativeRandFGMRES.hpp [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+                                  std::string memspace = "cuda");
+
+    LinSolverIterativeRandFGMRES(index_type restart,
+                                 real_type  tol,
+                                 index_type maxit,
+                                 index_type conv_cond,
+                                 MatrixHandler* matrix_handler,
+                                 VectorHandler* vector_handler, 
+                                  SketchingMethod rand_method, 
+                                 GramSchmidt*   gs,
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/LinSolverIterativeRandFGMRES.hpp:36]: I was so excited that it worked finally  that I forgot to indent :D

File: resolve/RandSketchingFWHT.cpp [hunk 8]
```diff
@@ -0,0 +1,153 @@
+#include "RandSketchingFWHT.hpp"
+#include <resolve/MemoryUtils.hpp>
+#include <resolve/vector/VectorHandler.hpp>
+#include <math.h>
+#ifdef RESOLVE_USE_HIP
+#include <resolve/hip/hipKernels.h>
+#endif
+#ifdef RESOLVE_USE_CUDA
+#include <resolve/cuda/cudaKernels.h>
+#endif
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/RandSketchingFWHT.cpp:10]: So what is your suggestion - i.e., we need Theta function (for instance) defined in cudaKernels and hipKernels - what is a better way to do it?

File: resolve/RandSketchingFWHT.hpp [hunk 9]
```diff
@@ -0,0 +1,38 @@
+#pragma once
+#include <resolve/Common.hpp>
+#include <resolve/vector/Vector.hpp>
```
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/RandSketchingFWHT.hpp:3]: so how do I get access to the vector ?

File: resolve/RandSketchingFWHT.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/RandSketchingFWHT.cpp:10]: Let's discuss this outside this PR. See #87.

File: resolve/RandSketchingFWHT.hpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/RandSketchingFWHT.hpp:3]: I would use forward declaration in the header file and include `Vector.hpp` in the source file.

[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/RandSketchingFWHT.hpp:3]: I did as you suggested, see newest commit

**Comment by kswirydo** [comment]
My lastest commit has a working version of cuda 11+ compatible SpSV triangular solve in ILU0 class. I also applied Slaven's dependency comments to 2 files.

File: examples/r_randGMRES.cpp [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+
+
+  ReSolve::matrix::Coo* A_coo;
+  ReSolve::matrix::Csr* A;
+  ReSolve::LinAlgWorkspaceHIP* workspace_HIP = new ReSolve::LinAlgWorkspaceHIP();
+  workspace_HIP->initializeHandles();
+  ReSolve::MatrixHandler* matrix_handler =  new ReSolve::MatrixHandler(workspace_HIP);
+  ReSolve::VectorHandler* vector_handler =  new ReSolve::VectorHandler(workspace_HIP);
+  real_type* rhs = nullptr;
+  real_type* x   = nullptr;
```
Comment (cameronrutherford) [inline examples/r_randGMRES.cpp:38]: This is endemic to ExaGO and HiOp, but I would be curious if we could get away from managing raw pointers like this, and have more of our examples use more modern C++ resource management techniques with shared/unique pointers where absolutely necessary, and then just having non-pointer variables here that are cleaned up without `delete`

Comment (cameronrutherford) [reply examples/r_randGMRES.cpp:38]: This same commend applies to other examples as well, and probably large amounts of the code...

File: examples/CMakeLists.txt [hunk 11]
```diff
@@ -48,17 +51,21 @@ if(RESOLVE_USE_HIP)
...
+  add_executable(gmres_rocsparse_rand.exe r_randGMRES.cpp)
+  target_link_libraries(gmres_rocsparse_rand.exe PRIVATE ReSolve)
 endif(RESOLVE_USE_HIP)
 
 # Install all examples in bin directory
 set(installable_executables klu_klu.exe klu_klu_standalone.exe)
 
 if(RESOLVE_USE_CUDA)
-  set(installable_executables ${installable_executables} klu_glu.exe klu_rf.exe klu_rf_fgmres.exe klu_glu_values_update.exe)        
+  set(installable_executables ${installable_executables} klu_glu.exe klu_rf.exe klu_rf_fgmres.exe klu_glu_values_update.exe gmres_cusparse_rand.exe)
```
Comment (cameronrutherford) [inline examples/CMakeLists.txt:64]: Not necessary to change, but CMake has in built list operands that are a little easier to read - https://cmake.org/cmake/help/latest/command/list.html

File: resolve/CMakeLists.txt [hunk 12]
```diff
@@ -37,13 +43,15 @@ set(ReSolve_HEADER_INSTALL
     LinSolverDirectCuSolverGLU.hpp
     LinSolverDirectCuSolverRf.hpp
     LinSolverDirectRocSolverRf.hpp
+    LinSolverDirectRocSparseILU0.hpp
+    LinSolverDirectCuSparseILU0.hpp
```
Comment (cameronrutherford) [inline resolve/CMakeLists.txt:47]: CUDA / ROCm specific sources should only be added conditionally to lists like this

File: resolve/LinSolverDirectCuSparseILU0.cpp [hunk 13]
```diff
@@ -0,0 +1,313 @@
...
+    mem_.deleteOnDevice(d_aux2_);
+    mem_.deleteOnDevice(d_ILU_vals_);
+  }
+
+  int LinSolverDirectCuSparseILU0::setup(matrix::Sparse* A,
+                                         matrix::Sparse*,
+                                         matrix::Sparse*,
+                                         index_type*,
+                                         index_type*,
+                                         vector_type* )
```
Comment (cameronrutherford) [inline resolve/LinSolverDirectCuSparseILU0.cpp:25]: If we were to move away from pointers in driver code, I think function signatures would stay the same, we would just be passing references instead

File: resolve/LinSolverDirectCuSparseILU0.hpp [hunk 14]
```diff
@@ -0,0 +1,73 @@
...
+    class Sparse;
+  }
+
+  class LinSolverDirectCuSparseILU0 : public LinSolverDirect 
+  {
+    using vector_type = vector::Vector;
+    
+    public: 
+      LinSolverDirectCuSparseILU0(LinAlgWorkspaceCUDA* workspace);
+      ~LinSolverDirectCuSparseILU0();
```
Comment (cameronrutherford) [inline resolve/LinSolverDirectCuSparseILU0.hpp:30]: Would probably need a copy / move constructor in many places to move away from pointers everywhere

File: resolve/LinSolverDirectRocSparseILU0.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (cameronrutherford) [reply resolve/LinSolverDirectRocSparseILU0.cpp:93]: +1 to `std::max`...

File: resolve/LinSolverIterativeFGMRES.cpp [hunk 15]
```diff
@@ -127,10 +135,10 @@ namespace ReSolve
     rnorm = 0.0;
     bnorm = vector_handler_->dot(rhs, rhs, memspace_);
     rnorm = vector_handler_->dot(d_V_, d_V_, memspace_);
-
     //rnorm = ||V_1||
     rnorm = sqrt(rnorm);
     bnorm = sqrt(bnorm);
+    printf("it 0: norm %16.16e \n", rnorm);
```
Comment (cameronrutherford) [inline resolve/LinSolverIterativeFGMRES.cpp:141]: Need to make sure these are conditionally disable-able for #2

File: resolve/LinSolverIterativeFGMRES.cpp [hunk 16]
```diff
@@ -215,6 +226,7 @@ namespace ReSolve
 
         // residual norm estimate
         rnorm = fabs(h_rs_[i + 1]);
+        printf("it %d: norm %16.16e \n",it, rnorm);
```
Comment (cameronrutherford) [inline resolve/LinSolverIterativeFGMRES.cpp:229]: Same here

File: resolve/LinSolverIterativeFGMRES.hpp [hunk 17]
```diff
@@ -37,11 +37,13 @@ namespace ReSolve
     index_type getMaxit();
     index_type getRestart();
     index_type getConvCond();
+    bool getFlexible();
```
Comment (cameronrutherford) [inline resolve/LinSolverIterativeFGMRES.hpp:40]:
```suggestion
    bool getFlexible() const;
```

We should probably make these pure getters const to reflect their behavior.

File: resolve/LinSolverIterativeFGMRES.hpp [hunk 18]
```diff
@@ -37,11 +37,13 @@ namespace ReSolve
...
 
     void setTol(real_type new_tol);
     void setMaxit(index_type new_maxit);
     void setRestart(index_type new_restart);
     void setConvCond(index_type new_conv_cond);
+    void setFlexible(bool new_flexible);
 
     real_type getFinalResidualNorm();
     real_type getInitResidualNorm();
```
Comment (cameronrutherford) [inline resolve/LinSolverIterativeFGMRES.hpp:49]:
```suggestion
    real_type getFinalResidualNorm() const;
    real_type getInitResidualNorm() const;
```

etc.

File: resolve/LinSolverIterativeRandFGMRES.hpp [hunk 19]
```diff
@@ -0,0 +1,102 @@
...
+
+    int solve(vector_type* rhs, vector_type* x);
+    int setup(matrix::Sparse* A);
+    int resetMatrix(matrix::Sparse* new_A); 
+    int setupPreconditioner(std::string name, LinSolverDirect* LU_solver);
+
+    real_type getTol();
+    index_type getMaxit();
+    index_type getRestart();
+    index_type getConvCond();
```
Comment (cameronrutherford) [inline resolve/LinSolverIterativeRandFGMRES.hpp:48]:
```suggestion
    index_type getMaxit() const;
    index_type getRestart() const;
    index_type getConvCond() const;
```

etc.

File: resolve/RandSketchingManager.hpp [hunk 20]
```diff
@@ -0,0 +1,36 @@
...
+      // Actual sketching process
+      virtual int Theta(vector_type* input, vector_type* output) = 0;
+
+      // Setup the parameters, sampling matrices, permuations, etc
+      virtual int setup(index_type n, index_type k) = 0;
+      virtual int reset() = 0;
+
+      virtual index_type getVectorSize();
+      virtual index_type getSketchSize();
+      virtual index_type getPaddedSize();
```
Comment (cameronrutherford) [inline resolve/RandSketchingManager.hpp:27]:
```suggestion
      virtual index_type getVectorSize() const;
      virtual index_type getSketchSize() const;
      virtual index_type getPaddedSize() const;
```

File: resolve/cuda/cudaKernels.cu [hunk 21]
```diff
@@ -1,4 +1,5 @@
 #include "cudaKernels.h"
+#include <cooperative_groups.h>
```
Comment (cameronrutherford) [inline resolve/cuda/cudaKernels.cu:2]: Is this for atomic operations?

File: runResolveOneMatrix [hunk 22]
```diff
@@ -0,0 +1,18 @@
+#!/bin/bash
```
Comment (cameronrutherford) [inline runResolveOneMatrix:1]: I don't like adding too many of these misc scripts and prefer adding to testing infra directly where possible.

**Review by cameronrutherford — CHANGES_REQUESTED** [review]
Looking good!

File: examples/r_randGMRES.cpp (hunk 10 above)
Comment (pelesh) [reply examples/r_randGMRES.cpp:38]: You are absolutely right. AFAIK GPU data needs to use raw pointers, but elsewhere we could take advantage of shared/unique pointers. To be tracked in #88.

File: resolve/LinSolverIterativeFGMRES.cpp (hunk 15 above)
Comment (pelesh) [reply resolve/LinSolverIterativeFGMRES.cpp:141]: This line has to go away. We have `Logger` class that can be conditionally disabled. @kswirydo, please remove or replace with Logger stream.

File: resolve/LinSolverIterativeFGMRES.cpp (hunk 16 above)
Comment (pelesh) [reply resolve/LinSolverIterativeFGMRES.cpp:229]: Use `Logger` instead or remove.

File: resolve/LinSolverIterativeFGMRES.hpp (hunk 17 above)
Comment (pelesh) [reply resolve/LinSolverIterativeFGMRES.hpp:40]: Tracked in #89

File: resolve/LinSolverIterativeFGMRES.hpp (hunk 18 above)
Comment (pelesh) [reply resolve/LinSolverIterativeFGMRES.hpp:49]: Tracked in #89

File: resolve/LinSolverIterativeRandFGMRES.hpp (hunk 19 above)
Comment (pelesh) [reply resolve/LinSolverIterativeRandFGMRES.hpp:48]: See #89

File: resolve/RandSketchingManager.hpp (hunk 20 above)
Comment (pelesh) [reply resolve/RandSketchingManager.hpp:27]: See #89

File: resolve/LinSolverDirectRocSparseILU0.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (kswirydo) [reply resolve/LinSolverDirectRocSparseILU0.cpp:93]: this is removed now - I allocate 3 separate buffers in the new version

File: resolve/cuda/cudaKernels.cu (hunk 21 above)
Comment (kswirydo) [reply resolve/cuda/cudaKernels.cu:2]: No. This stuff allows you to synchronize smaller groups of treads (not the entire block). It was added not that long ago. [See here](https://developer.nvidia.com/blog/cooperative-groups/)

File: resolve/CMakeLists.txt (hunk 12 above)
Comment (kswirydo) [reply resolve/CMakeLists.txt:47]: I dont know how to do it in cmake.

Comment (cameronrutherford) [reply resolve/CMakeLists.txt:47]: https://github.com/ORNL/ReSolve/blob/develop/resolve/CMakeLists.txt#L76 - we have examples of CUDA / ROCm conditionals already in code

File: runResolveOneMatrix (hunk 22 above)
Comment (kswirydo) [reply runResolveOneMatrix]: removed

File: resolve/LinSolverIterativeFGMRES.cpp (hunk 15 above)
Comment (kswirydo) [reply resolve/LinSolverIterativeFGMRES.cpp:141]: addressed in newest commit

File: resolve/LinSolverIterativeFGMRES.cpp (hunk 16 above)
Comment (kswirydo) [reply resolve/LinSolverIterativeFGMRES.cpp:229]: addressed in newest commit

**Comment by ryandanehy** [comment]
@kswirydo to get this to run PNNL tests the pr conflicts need to be fixed (probally best to do it through rebase). Then PNNL tests should start running.

**Comment by pelesh** [comment]
> @kswirydo to get this to run PNNL tests the pr conflicts need to be fixed (probally best to do it through rebase). Then PNNL tests should start running.

It seems all we needed was to rebase to `develop`, not sure why.

File: resolve/LinSolverDirectRocSparseILU0.hpp [hunk 23]
```diff
@@ -0,0 +1,67 @@
...
+#include "LinSolver.hpp"
+#include <resolve/MemoryUtils.hpp>
+#include <resolve/workspace/LinAlgWorkspace.hpp>
+
+#include <rocsparse/rocsparse.h>
+//#include <rocblas/rocblas.h>
+#include <rocsolver/rocsolver.h>
+#include <hip/hip_runtime.h>
+#include <roctracer/roctx.h>
+
```
Comment (pelesh) [inline resolve/LinSolverDirectRocSparseILU0.hpp:13]: Do we need roctracer here?
```suggestion

```

Comment (pelesh) [reply resolve/LinSolverDirectRocSparseILU0.hpp:13]: This trips tests on Incline, I am not sure how other tests pass.

Comment (ryandanehy) [reply resolve/LinSolverDirectRocSparseILU0.hpp:13]: Could have something to do with incline build env. Just a guess though.

Comment (ryandanehy) [reply resolve/LinSolverDirectRocSparseILU0.hpp:13]: @cameronrutherford  any ideas?

File: resolve/CMakeLists.txt (hunk 12 above)
Comment (pelesh) [reply resolve/CMakeLists.txt:47]: @cameronrutherford, I think we are okay here. We decided to install all header files for all configurations regardless. If you scroll a few lines up following the link you provided and you will find it there, as well. We could change the CMake code to install only headers that have matching libraries built (that would be a better solution I think). I will spawn another issue.

File: resolve/LinSolverDirectRocSparseILU0.hpp (hunk 23 above)
Comment (cameronrutherford) [reply resolve/LinSolverDirectRocSparseILU0.hpp:13]: Nuke header per #68

File: resolve/CMakeLists.txt (hunk 12 above)
Comment (pelesh) [reply resolve/CMakeLists.txt:47]: Tracked in #91.

File: resolve/LinSolverDirectRocSparseILU0.hpp (hunk 23 above)
Comment (pelesh) [reply resolve/LinSolverDirectRocSparseILU0.hpp:13]: > Nuke header per #68

@kswirydo, you have the honor ...

File: resolve/LinSolverDirectRocSparseILU0.cpp (hunk 1 above)
Comment (pelesh) [inline resolve/LinSolverDirectRocSparseILU0.cpp:93]: I believe this could be much nicer fix for the conversion warnings:
```suggestion
    size_t buffer_size = std::max(buffer_size_A, std::max(buffer_size_L, buffer_size_U));
```

Comment (pelesh) [reply resolve/LinSolverDirectRocSparseILU0.cpp:93]: CC @cameronrutherford

[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/LinSolverDirectRocSparseILU0.cpp:93]: I will resolve this thread in favor of the new one with proposed solution.

**Review by pelesh — CHANGES_REQUESTED** [review]
Remaining items before this can be merged:
- [x] Add functionality tests for randomized (F)GMRES on AMD and NVIDIA GPUs
- [x] Use STL math on the host (this will take care of a big chunk of warnings)
- [x] Fix other warnings
- [x] Remove `roctx.h` header from `LinSolverDirectRocSparseILU0.hpp`.

Almost there ;)

**Comment by cameronrutherford** [comment]
> I fixed our little mishap with rebasing. All is needed to do is to:
> 
> * Generate test matrices _inside_ functionality tests. This is lesser evil than keeping 170MB test matrix in a repo.
> * Add again randomized solvers tests to CMake build and testing.

GitHub shouldn't allow files that big. pre-commit can also help detect when these large files are added, and custom thresholds can be configured cc @ryandanehy

**Review by pelesh — APPROVED** [review]
All review issues have been addressed. Merge once CI tests pass.
