### PR TITLE
SystemSolver Interface updates

### LINKED ISSUE #123: "update" functions assign data ownership incorrectly
Linear algebra methods that update data in local objects check if memory is allocated and if not they allocate memory underneath so they can copy/update data on user-specified device. However, they assign ownership of that data upon copy and not upon allocation. If the data exists and is not owned by the local object, the ownership will be incorrectly assigned to the local who will eventually try to delete it. This could cause double-delete segfault.

### PR DESCRIPTION
**Pull request by pelesh**
Updates to `SystemSolver` class:
- Add methods to compute residual norms.
- Improve configuration parameter management.
- Create portable `SystemSolver` usage example(s).
- Prep work to enable FGMRES on CPU.
- Closes #123

### CODE REVIEW

File: resolve/matrix/Coo.cpp [hunk 1]
```diff
@@ -84,27 +87,33 @@ namespace ReSolve
 
     if (memspaceOut == memory::HOST) {
       //check if cpu data allocated	
-      if (h_row_data_ == nullptr) {
-        this->h_row_data_ = new index_type[nnz_current];
+      if ((h_row_data_ == nullptr) != (h_col_data_ == nullptr)) {
+        out::error() << "In Coo::updateData one of host row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Coo.cpp:91]: I would put a warning here, not error.

File: resolve/matrix/Coo.cpp [hunk 2]
```diff
@@ -84,27 +87,33 @@ namespace ReSolve
...
+        owns_cpu_vals_ = true;
       }
     }
 
     if (memspaceOut == memory::DEVICE) {
       //check if cuda data allocated
-      if (d_row_data_ == nullptr) {
-        mem_.allocateArrayOnDevice(&d_row_data_, nnz_current);
+      if ((d_row_data_ == nullptr) != (d_col_data_ == nullptr)) {
+        out::error() << "In Coo::updateData one of device row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Coo.cpp:107]: same here.

File: resolve/matrix/Coo.cpp [hunk 3]
```diff
@@ -196,40 +197,42 @@ namespace ReSolve
     switch (memspaceOut) {
       case HOST:
         if ((d_data_updated_ == true) && (h_data_updated_ == false)) {
-          if (h_row_data_ == nullptr) {
-            h_row_data_ = new index_type[nnz_current];      
+          if ((h_row_data_ == nullptr) != (h_col_data_ == nullptr)) {
+            out::error() << "In Coo::copyData one of host row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Coo.cpp:201]: and here.

File: resolve/matrix/Coo.cpp [hunk 4]
```diff
@@ -196,40 +197,42 @@ namespace ReSolve
...
-          owns_cpu_data_ = true;
-          owns_cpu_vals_ = true;
         }
         return 0;
       case DEVICE:
         if ((d_data_updated_ == false) && (h_data_updated_ == true)) {
-          if (d_row_data_ == nullptr) {
-            mem_.allocateArrayOnDevice(&d_row_data_, nnz_current);
+          if ((d_row_data_ == nullptr) != (d_col_data_ == nullptr)) {
+            out::error() << "In Coo::copyData one of device row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Coo.cpp:221]: and here

File: resolve/matrix/Csc.cpp [hunk 5]
```diff
@@ -80,27 +83,33 @@ namespace ReSolve
 
     if (memspaceOut == memory::HOST) {
       //check if cpu data allocated
-      if (h_col_data_ == nullptr) {
-        this->h_col_data_ = new index_type[n_ + 1];
+      if ((h_row_data_ == nullptr) != (h_col_data_ == nullptr)) {
+        out::error() << "In Csc::updateData one of host row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Csc.cpp:87]: and here. And I would let it slide, just give a warning (also warn about memory leak)

File: resolve/matrix/Csr.cpp [hunk 6]
```diff
@@ -97,27 +97,33 @@ namespace ReSolve
 
     if (memspaceOut == memory::HOST) {
       //check if cpu data allocated
-      if (h_row_data_ == nullptr) {
-        this->h_row_data_ = new index_type[n_ + 1];
+      if ((h_row_data_ == nullptr) != (h_col_data_ == nullptr)) {
+        out::error() << "In Csr::updateData one of host row or column data is null!\n";
```
Comment (kswirydo) [inline resolve/matrix/Csr.cpp:101]: and here, of course.

File: tests/functionality/testKLU_Rf_FGMRES.cpp [hunk 7]
```diff
@@ -267,7 +281,7 @@ int main(int argc, char *argv[])
   delete [] rhs;
   delete vec_r;
   delete vec_x;
-  delete workspace_CUDA;
+  // delete workspace_HIP;
```
Comment (kswirydo) [inline tests/functionality/testKLU_Rf_FGMRES.cpp:284]: shouldnt you have `delete workspace;` ?

File: tests/functionality/testSysRandGMRES.cpp [hunk 8]
```diff
@@ -0,0 +1,264 @@
...
+            << solver->getIterativeSolver().getFinalResidualNorm()/norm_b << " \n"
+            << "\t Number of iterations                                 : " 
+            << solver->getIterativeSolver().getNumIter() << "\n";
+
+  if ((final_norm_first/norm_b > 1e-11) || (solver->getIterativeSolver().getFinalResidualNorm()/norm_b > 1e-11 )) {
+    std::cout << "Result inaccurate!\n";
+    error_sum++;
+  }
+  if (error_sum == 0) {
+    std::cout<<"Test 5 (randomized GMRES) PASSED"<<std::endl<<std::endl;;
```
Comment (kswirydo) [inline tests/functionality/testSysRandGMRES.cpp:171]: it is still test 5?

File: tests/functionality/testSysRandGMRES.cpp [hunk 9]
```diff
@@ -0,0 +1,264 @@
...
+  } else {
+    std::cout<<"Test 5 (randomized GMRES) FAILED, error sum: "<<error_sum<<std::endl<<std::endl;;
+  }
+
+  delete A;
```
Comment (kswirydo) [inline tests/functionality/testSysRandGMRES.cpp:176]: dont you need to delete the system solvr object too?

Comment (pelesh) [reply tests/functionality/testSysRandGMRES.cpp:176]: Solver object is created on the stack.

File: tests/functionality/testKLU_Rf_FGMRES.cpp (hunk 7 above)
Comment (pelesh) [reply tests/functionality/testKLU_Rf_FGMRES.cpp:284]: workspace is created on the stack.

File: resolve/matrix/Coo.cpp (hunk 1 above)
Comment (pelesh) [reply resolve/matrix/Coo.cpp:91]: The error is more appropriate here, because next function will segfault if one of the two pointers is null. The error message merely explains why the execution fails.

File: resolve/SystemSolver.cpp [hunk 10]
```diff
@@ -97,30 +122,49 @@ namespace ReSolve
...
+
+    if (precondition_method_ != "none") {
+      delete preconditioner_;
+    }
 
     delete matrixHandler_;
     delete vectorHandler_;
   }
 
   int SystemSolver::setMatrix(matrix::Sparse* A)
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/SystemSolver.cpp:147]: It sets the pointer to matrix `A` in the SystemSolver class. This is the most convenient place to set up _iterative_ linear solver, as well.

File: resolve/SystemSolver.cpp [hunk 11]
```diff
@@ -132,22 +176,42 @@ namespace ReSolve
   int SystemSolver::initialize()
   {
     // First delete old objects
-    if (factorizationSolver_)
+    if (factorizationSolver_) {
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/SystemSolver.cpp:179]: The initialize function is supposed to destroy everything and start anew. A couple of possible future improvements:
- Print warning when destroying objects. If used correctly, `initialize()` should never need to delete anything.
- Create separate methods for creating components of the system solver. These will be easier to manage and less brute force.

File: resolve/SystemSolver.cpp [hunk 12]
```diff
@@ -132,22 +176,42 @@ namespace ReSolve
...
+      iterativeSolver_ = nullptr;
+    }
+    if (gs_) {
+      delete gs_;
+      gs_ = nullptr;
+    }
     
     // Create factorization solver
-    if (factorizationMethod_ == "klu") {
+    if (factorizationMethod_ == "none") {
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/SystemSolver.cpp:201]: You are absolutely right, we should have enums and switch statements here. It is on to-do list.

File: resolve/SystemSolver.cpp [hunk 13]
```diff
@@ -132,22 +176,42 @@ namespace ReSolve
...
       out::error() << "Unrecognized factorization " << factorizationMethod_ << "\n";
       return 1;
     }
 
     // Create refactorization solver
-    if (refactorizationMethod_ == "klu") {
-      // do nothing for now
+    if (refactorizationMethod_ == "none") {
+      // do nothing
+    } else if (refactorizationMethod_ == "klu") {
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/SystemSolver.cpp:213]: Do nothing is appropriate when refactorization and factorization solvers are the same. We don't want two instances of KLU.

File: resolve/SystemSolver.cpp [hunk 14]
```diff
@@ -248,92 +342,115 @@ namespace ReSolve
 
     if (L_ == nullptr) {
       out::warning() << "Factorization failed, cannot extract factors ...\n";
-      status = 1;
+      status += 1;
```
[the remark this answers is not in the document]
Comment (pelesh) [reply resolve/SystemSolver.cpp:345]: Yes, it should.

File: tests/functionality/testSysRandGMRES.cpp (hunk 8 above)
Comment (pelesh) [reply tests/functionality/testSysRandGMRES.cpp]: Removed hard-wired numbers in tests. CTest is numbering them.
