### PR TITLE
Fixed include files

### LINKED ISSUE #72: Missing header file include in the installed include files
For the HIP version:
The include file `resolve/LinSolverDirectRocSolverRf.hpp` needs to add `#include <resolve/matrix/Csr.hpp>`.

For the CUDA version:
The include file `resolve/LinSolverDirectCuSolverGLU.hpp` needs to add `#include <resolve/workspace/LinAlgWorkspace.hpp>`

### PR DESCRIPTION
**Pull request by maksud**
Added the required include lines.

Fixes #72

### CODE REVIEW

File: resolve/LinSolverDirectCuSolverGLU.hpp [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include "LinSolver.hpp"
 #include "cusolver_defs.hpp"
 #include <resolve/MemoryUtils.hpp>
+#include <resolve/workspace/LinAlgWorkspace.hpp>
```
Comment (pelesh) [inline resolve/LinSolverDirectCuSolverGLU.hpp:7]: This should not be included here. Use forward declaration instead. The source file should have specific includes.
```suggestion

```

Comment (pelesh) [reply resolve/LinSolverDirectCuSolverGLU.hpp:7]: The bug here is on line 22. The forward declaration should be (I think):
```c++
  class LinAlgWorkspaceCUDA;
```

File: resolve/LinSolverDirectRocSolverRf.hpp [hunk 2]
```diff
@@ -8,6 +8,7 @@
 #include <rocblas/rocblas.h>
 #include <rocsolver/rocsolver.h>
 #include <hip/hip_runtime.h>
+#include <resolve/matrix/Csr.hpp>
```
Comment (pelesh) [inline resolve/LinSolverDirectRocSolverRf.hpp:12]: Use forward declaration here. If necessary, add this include to the source file.
```suggestion

```

**Review by pelesh — CHANGES_REQUESTED** [review]
Please use forward declarations in header files and include headers to the source files as needed. We need to keep build dependencies minimal in order to maintain code portability.

**Review by pelesh — APPROVED** [review]
lgtm
